/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReminderRouteImport } from './routes/reminder'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as PegawaiRouteImport } from './routes/pegawai'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as KgbRouteImport } from './routes/kgb'
import { Route as KenaikanPangkatRouteImport } from './routes/kenaikan-pangkat'
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApprovalRouteImport } from './routes/approval'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PegawaiIdRouteImport } from './routes/pegawai.$id'
import { Route as MasterJabatanRouteImport } from './routes/master.jabatan'
import { Route as MasterGolonganRouteImport } from './routes/master.golongan'

const ReminderRoute = ReminderRouteImport.update({
  id: '/reminder',
  path: '/reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PegawaiRoute = PegawaiRouteImport.update({
  id: '/pegawai',
  path: '/pegawai',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const KgbRoute = KgbRouteImport.update({
  id: '/kgb',
  path: '/kgb',
  getParentRoute: () => rootRouteImport,
} as any)
const KenaikanPangkatRoute = KenaikanPangkatRouteImport.update({
  id: '/kenaikan-pangkat',
  path: '/kenaikan-pangkat',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalRoute = ApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PegawaiIdRoute = PegawaiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PegawaiRoute,
} as any)
const MasterJabatanRoute = MasterJabatanRouteImport.update({
  id: '/master/jabatan',
  path: '/master/jabatan',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterGolonganRoute = MasterGolonganRouteImport.update({
  id: '/master/golongan',
  path: '/master/golongan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approval': typeof ApprovalRoute
  '/dashboard': typeof DashboardRoute
  '/kalender': typeof KalenderRoute
  '/kenaikan-pangkat': typeof KenaikanPangkatRoute
  '/kgb': typeof KgbRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/pegawai': typeof PegawaiRouteWithChildren
  '/pengaturan': typeof PengaturanRoute
  '/profile': typeof ProfileRoute
  '/reminder': typeof ReminderRoute
  '/master/golongan': typeof MasterGolonganRoute
  '/master/jabatan': typeof MasterJabatanRoute
  '/pegawai/$id': typeof PegawaiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approval': typeof ApprovalRoute
  '/dashboard': typeof DashboardRoute
  '/kalender': typeof KalenderRoute
  '/kenaikan-pangkat': typeof KenaikanPangkatRoute
  '/kgb': typeof KgbRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/pegawai': typeof PegawaiRouteWithChildren
  '/pengaturan': typeof PengaturanRoute
  '/profile': typeof ProfileRoute
  '/reminder': typeof ReminderRoute
  '/master/golongan': typeof MasterGolonganRoute
  '/master/jabatan': typeof MasterJabatanRoute
  '/pegawai/$id': typeof PegawaiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approval': typeof ApprovalRoute
  '/dashboard': typeof DashboardRoute
  '/kalender': typeof KalenderRoute
  '/kenaikan-pangkat': typeof KenaikanPangkatRoute
  '/kgb': typeof KgbRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/pegawai': typeof PegawaiRouteWithChildren
  '/pengaturan': typeof PengaturanRoute
  '/profile': typeof ProfileRoute
  '/reminder': typeof ReminderRoute
  '/master/golongan': typeof MasterGolonganRoute
  '/master/jabatan': typeof MasterJabatanRoute
  '/pegawai/$id': typeof PegawaiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approval'
    | '/dashboard'
    | '/kalender'
    | '/kenaikan-pangkat'
    | '/kgb'
    | '/laporan'
    | '/login'
    | '/pegawai'
    | '/pengaturan'
    | '/profile'
    | '/reminder'
    | '/master/golongan'
    | '/master/jabatan'
    | '/pegawai/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approval'
    | '/dashboard'
    | '/kalender'
    | '/kenaikan-pangkat'
    | '/kgb'
    | '/laporan'
    | '/login'
    | '/pegawai'
    | '/pengaturan'
    | '/profile'
    | '/reminder'
    | '/master/golongan'
    | '/master/jabatan'
    | '/pegawai/$id'
  id:
    | '__root__'
    | '/'
    | '/approval'
    | '/dashboard'
    | '/kalender'
    | '/kenaikan-pangkat'
    | '/kgb'
    | '/laporan'
    | '/login'
    | '/pegawai'
    | '/pengaturan'
    | '/profile'
    | '/reminder'
    | '/master/golongan'
    | '/master/jabatan'
    | '/pegawai/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalRoute: typeof ApprovalRoute
  DashboardRoute: typeof DashboardRoute
  KalenderRoute: typeof KalenderRoute
  KenaikanPangkatRoute: typeof KenaikanPangkatRoute
  KgbRoute: typeof KgbRoute
  LaporanRoute: typeof LaporanRoute
  LoginRoute: typeof LoginRoute
  PegawaiRoute: typeof PegawaiRouteWithChildren
  PengaturanRoute: typeof PengaturanRoute
  ProfileRoute: typeof ProfileRoute
  ReminderRoute: typeof ReminderRoute
  MasterGolonganRoute: typeof MasterGolonganRoute
  MasterJabatanRoute: typeof MasterJabatanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reminder': {
      id: '/reminder'
      path: '/reminder'
      fullPath: '/reminder'
      preLoaderRoute: typeof ReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pegawai': {
      id: '/pegawai'
      path: '/pegawai'
      fullPath: '/pegawai'
      preLoaderRoute: typeof PegawaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kgb': {
      id: '/kgb'
      path: '/kgb'
      fullPath: '/kgb'
      preLoaderRoute: typeof KgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kenaikan-pangkat': {
      id: '/kenaikan-pangkat'
      path: '/kenaikan-pangkat'
      fullPath: '/kenaikan-pangkat'
      preLoaderRoute: typeof KenaikanPangkatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval': {
      id: '/approval'
      path: '/approval'
      fullPath: '/approval'
      preLoaderRoute: typeof ApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pegawai/$id': {
      id: '/pegawai/$id'
      path: '/$id'
      fullPath: '/pegawai/$id'
      preLoaderRoute: typeof PegawaiIdRouteImport
      parentRoute: typeof PegawaiRoute
    }
    '/master/jabatan': {
      id: '/master/jabatan'
      path: '/master/jabatan'
      fullPath: '/master/jabatan'
      preLoaderRoute: typeof MasterJabatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/golongan': {
      id: '/master/golongan'
      path: '/master/golongan'
      fullPath: '/master/golongan'
      preLoaderRoute: typeof MasterGolonganRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PegawaiRouteChildren {
  PegawaiIdRoute: typeof PegawaiIdRoute
}

const PegawaiRouteChildren: PegawaiRouteChildren = {
  PegawaiIdRoute: PegawaiIdRoute,
}

const PegawaiRouteWithChildren =
  PegawaiRoute._addFileChildren(PegawaiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalRoute: ApprovalRoute,
  DashboardRoute: DashboardRoute,
  KalenderRoute: KalenderRoute,
  KenaikanPangkatRoute: KenaikanPangkatRoute,
  KgbRoute: KgbRoute,
  LaporanRoute: LaporanRoute,
  LoginRoute: LoginRoute,
  PegawaiRoute: PegawaiRouteWithChildren,
  PengaturanRoute: PengaturanRoute,
  ProfileRoute: ProfileRoute,
  ReminderRoute: ReminderRoute,
  MasterGolonganRoute: MasterGolonganRoute,
  MasterJabatanRoute: MasterJabatanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
